### ISSUE TITLE
pool send rewards to an unknown address

### ISSUE THREAD

**Issue by renok1** [hacash/miner#11] opened 2021-08-25 13:11 UTC
why does the pool send rewards to an unknown address 12BZKnrbV3hWP53HJcUeouycDtyPhyySnj

**Comment by dwymi02** [comment] 2021-09-09 20:03
In an effort to move this issue forward, issue has been open for fifteen days now, it seems additional information is required.
Not trying to split hairs, but the address [https://explorer.hacash.org/address/12BZKnrbV3hWP53HJcUeouycDtyPhyySnj] appears valid.

HAC Amount: ㄜ64,751,751,295:240
Diamond Amount: 26

In order to attempt addressing your reported problem, it will be necessary to provide information that will allow us to understand what the reported problem is.
To that end, please provide us with the following information:

+ The pool name/IP Address/pool wallet address where the problem is being reported
+ The HAC block number the suspect transaction occurred
+ Any screenshots showing the [CompleteRewards], [DeservedRewards] and [UnconfirmedRewards] for the affected pool and the target wallet address
+ Any additional information you feel will help us to understand the problem reported
+ Is this a one time occurrence, or do you notice a pattern of being repeated?

Look forward to your helping us by providing more information regarding this problem.


THANX(MKD).

**Comment by renok1** [comment] 2021-09-10 06:05
https://disk.yandex.ru/d/pDC10t3It2yZNQ
https://disk.yandex.ru/d/TcNiIdAIQvcw-w
these are files from my computer, from which I ran the pull

**Comment by dwymi02** [comment] 2021-11-19 01:13
renok1,
it appears those files no longer exist at the location listed.
Please upload the files again, I will endeavor to grab them as soon as they have been uploaded.
I really want to bring this issue to resolution.
Appreciate your efforts in this regard.

THANX(MKD).

**Comment by renok1** [comment] 2021-11-19 03:11
The files can be downloaded from the link:
https://disk.yandex.ru/d/TcNiIdAIQvcw-w
https://disk.yandex.ru/d/pDC10t3It2yZNQ

**Comment by dwymi02** [comment] 2021-11-19 16:28
renok1,

I have downloaded all the files from hacash.zip
The files I have are as follows:

6884232 Nov 19  2021 cmdwallet_2021_02_12.exe
    910 Nov 19  2021 hacash.config.ini
    224 Nov 19  2021 hacash_mainnet_data/
    456 Nov 19  2021 hacash_minerpool_data/
9071720 Nov 19  2021 miner_2021_02_12.exe
5370728 Nov 19  2021 poolminer_2021-0410.exe
     98 Nov 19  2021 poolworker.config.ini

The [poolworker.config.ini] points to a local pool [192.168...]

The [hacash.config.ini] is set for solo mining,
[miner]        -> true
[minerpool]    -> false
[minerserver]  -> false
[diamondminer] -> false

The [hacash_mainnet_data/] has v4 and v6 data
If you are still running this configuration, please upgrade your executables to latest available.
The latest Hacash executables can be downloaded from [https://github.com/hacash/miner/blob/master/doc/software_release_log.md]

Lastest release log:
Version: 0.1.7-repair2 (2021.11.17.02)

update log:

[1] FIX FORK OF BLOCK HEIGHT 292715!


Looking at the [https://explorer.hacash.org/address/12BZKnrbV3hWP53HJcUeouycDtyPhyySnj]
I found seven instances where your [miner] [1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta] reported a transfer to [12BZKnrbV3hWP53HJcUeouycDtyPhyySnj]

Block：268914 From：1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta To： 12BZKnr… Amt：ㄜ199,999:243   Time：2021-08-26 02:51
Block：268832 From：1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta To： 12BZKnr… Amt：ㄜ202,035:243   Time：2021-08-25 21:15
Block：268628 From：1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta To： 12BZKnr… Amt：ㄜ19,999:244    Time：2021-08-25 03:08
Block：268556 From：1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta To： 12BZKnr… Amt：ㄜ19,999:244    Time：2021-08-24 21:15
Block：268318 From：1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta To： 12BZKnr… Amt：ㄜ2:248         Time：2021-08-23 20:22
Block：268049 From：1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta To： 12BZKnr… Amt：ㄜ9,980,001:240 Time：2021-08-22 19:53
Block：267905 From：1EuphBBvrZTAyqwDoA86wbXn5kDtZcJDta To： 12BZKnr… Amt：ㄜ9,980,001:240 Time：2021-08-22 11:09

This provides the when this happened, I just do not know the why the transfer occurred.

In the files provided, you also provided the [hacash_mainnet_data/] and [hacash_minerpool_data/]
I will need to determine if we have any tools that can analyze the data.
On this I will let you know if any form of analysis can be performed.

With regards to the [hacash_minerpool_data/], this indicates that you either run or have run a Pool Server.
I was able to review the file [hacash/hacash_minerpool_data/LOG] file.

The date stamp in the file is dated from [Aug 21, 2021] to [Aug 24, 2021]
This file did not provide any useful information that would help explain the problem you have reported.

Following is from my prior request for documentation:

    * The pool name/IP Address/pool wallet address where the problem is being reported
    * The HAC block number the suspect transaction occurred
    * Any screenshots showing the [CompleteRewards], [DeservedRewards] and [UnconfirmedRewards] for the affected pool and the target wallet address
    * Any additional information you feel will help us to understand the problem reported
    * Is this a one time occurrence, or do you notice a pattern of being repeated?

    * Additionally, if you can provide the log from the Pool Server this would be helpful

If you can provide this information, please double check to ensure that no information regarding your wallet is inadvertently transferred.

Since the time of the reported issue, was back in Aug-2021, if this reported problem has not reoccurred, it would be prudent to close the issue.
Should the problem reoccur again, then you could gather as much of the requested data as is possible.

I will leave this issue open for another week.
If I do not hear back from you, I will close this issue.
If you can provide the information I will gladly review it, then provide an update.

If the issue is closed and the problem reoccurs again, open a new issue, provide as much of the requested documentation so we can address this problem.


THANX(MKD).

**Comment by dwymi02** [comment] 2021-12-07 00:46
Per my last comment, since no new documentation has been submitted for review, this issue will be closed, with the proviso that should the problem reoccur, requested documentation will be submitted, reviewed an acted upon, based on what the documentation reveals.

Should this problem reoccur, please open a new ticket, provide us with the documentation and someone from Hacash will review it, then take the necessary steps in addressing this reported problem.

For now, this issue will be closed.


THANX(MKD).

**Closed by dwymi02** 2021-12-07 00:46 UTC
